//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction_v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblBid
    {
        public int Id { get; set; }
        public string CurrentBidder { get; set; }

        [Display(Name = "Bid")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Enter Bid")]
        public decimal CurrentBid { get; set; }
        public int ProductID { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
