//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction_v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblBids = new HashSet<tblBid>();
        }

        public int ProductID { get; set; }

        [Display(Name = "Product Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Enter Product Name")]
        public string ProductName { get; set; }

        [Display(Name = "Category")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Select Category")]
        public string ProductCategory { get; set; }

        [Display(Name = "Image")]
        public string PicUrl { get; set; }

        [Display(Name = "Starting Price")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Enter Price")]
        public decimal ProductPrice { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Select Closing Time")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime ProductClose { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBid> tblBids { get; set; }
    }
}
